enum QueryKeys {
	GET_TRANSACTIONS = "GET_TRANSACTIONS",
	GET_CONTACTS = "GET_CONTACTS",
	GET_MERCHANTS = "GET_MERCHANTS",
	GET_USERS = "GET_USERS",
	GET_CHANNELS = "GET_CHANNELS",
	GET_TOKEN = "GET_TOKEN",
	GET_ANALYSTRANK = "GET_ANALYSTRANK",
	GET_RECENTFRAUD = "GET_RECENTFRAUD",
	GET_MERCHANTRANK = "GET_MERCHANTRANK",
	GET_STATISTIC = "GET_STATISTIC",
}

export default QueryKeys;
